export const FETCH_FILMS_REQUEST = "FETCH_FILMS_REQUEST";
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";
export const FETCH_USER_FILMS = "FETCH_USER_FILMS";
export const CLEAR_USER_FILMS = "CLEAR_USER_FILMS";
export const REQUEST_USER_FILMS = "REQUEST_USER_FILMS";
